// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks_test.go -package=node
//

// Package node is a generated GoMock package.
package trie

import (
	"reflect"

	"go.uber.org/mock/gomock"

	"github.com/amarin/gomorphy/pkg/size"
)

// MockalphabetInterface is a mock of alphabetInterface interface.
type MockalphabetInterface[A size.Alphabet] struct {
	ctrl     *gomock.Controller
	recorder *MockalphabetInterfaceMockRecorder[A]
	isgomock struct{}
}

// MockalphabetInterfaceMockRecorder is the mock recorder for MockalphabetInterface.
type MockalphabetInterfaceMockRecorder[A size.Alphabet] struct {
	mock *MockalphabetInterface[A]
}

// NewMockalphabetInterface creates a new mock instance.
func NewMockalphabetInterface[A size.Alphabet](ctrl *gomock.Controller) *MockalphabetInterface[A] {
	mock := &MockalphabetInterface[A]{ctrl: ctrl}
	mock.recorder = &MockalphabetInterfaceMockRecorder[A]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockalphabetInterface[A]) EXPECT() *MockalphabetInterfaceMockRecorder[A] {
	return m.recorder
}

// Get mocks base method.
func (m *MockalphabetInterface[A]) Get(char rune) (A, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", char)
	ret0, _ := ret[0].(A)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockalphabetInterfaceMockRecorder[A]) Get(char any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockalphabetInterface[A])(nil).Get), char)
}

// GetOrCreate mocks base method.
func (m *MockalphabetInterface[A]) GetOrCreate(char rune) (A, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", char)
	ret0, _ := ret[0].(A)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockalphabetInterfaceMockRecorder[A]) GetOrCreate(char any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockalphabetInterface[A])(nil).GetOrCreate), char)
}

// String mocks base method.
func (m *MockalphabetInterface[A]) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockalphabetInterfaceMockRecorder[A]) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockalphabetInterface[A])(nil).String))
}
