// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source=deps.go -destination=mocks_test.go -package=trie
//

// Package trie is a generated GoMock package.
package trie

import (
	io "io"
	reflect "reflect"

	size "github.com/amarin/gomorphy/pkg/size"
	gomock "go.uber.org/mock/gomock"
)

// MockAlphabet is a mock of Alphabet interface.
type MockAlphabet[A size.Alphabet] struct {
	ctrl     *gomock.Controller
	recorder *MockAlphabetMockRecorder[A]
	isgomock struct{}
}

// MockAlphabetMockRecorder is the mock recorder for MockAlphabet.
type MockAlphabetMockRecorder[A size.Alphabet] struct {
	mock *MockAlphabet[A]
}

// NewMockAlphabet creates a new mock instance.
func NewMockAlphabet[A size.Alphabet](ctrl *gomock.Controller) *MockAlphabet[A] {
	mock := &MockAlphabet[A]{ctrl: ctrl}
	mock.recorder = &MockAlphabetMockRecorder[A]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlphabet[A]) EXPECT() *MockAlphabetMockRecorder[A] {
	return m.recorder
}

// Get mocks base method.
func (m *MockAlphabet[A]) Get(char rune) (A, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", char)
	ret0, _ := ret[0].(A)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAlphabetMockRecorder[A]) Get(char any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAlphabet[A])(nil).Get), char)
}

// GetOrCreate mocks base method.
func (m *MockAlphabet[A]) GetOrCreate(char rune) (A, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", char)
	ret0, _ := ret[0].(A)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockAlphabetMockRecorder[A]) GetOrCreate(char any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockAlphabet[A])(nil).GetOrCreate), char)
}

// ReadFrom mocks base method.
func (m *MockAlphabet[A]) ReadFrom(r io.Reader) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFrom", r)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFrom indicates an expected call of ReadFrom.
func (mr *MockAlphabetMockRecorder[A]) ReadFrom(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFrom", reflect.TypeOf((*MockAlphabet[A])(nil).ReadFrom), r)
}

// String mocks base method.
func (m *MockAlphabet[A]) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockAlphabetMockRecorder[A]) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockAlphabet[A])(nil).String))
}

// WriteTo mocks base method.
func (m *MockAlphabet[A]) WriteTo(w io.Writer) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteTo", w)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteTo indicates an expected call of WriteTo.
func (mr *MockAlphabetMockRecorder[A]) WriteTo(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteTo", reflect.TypeOf((*MockAlphabet[A])(nil).WriteTo), w)
}
