// Command embed shows shipping a dictionary inside the binary: names.dat is
// compiled in with //go:embed and opened with OpenBytes — no file on disk
// at run time and no mmap, so it also works on Windows, where Open does
// not. names.dat is generated by `go run ./examples/embed/gen`.
//
// Run: go run ./examples/embed
package main

import (
	_ "embed"
	"fmt"
	"log"

	"github.com/amarin/gomorphy/pkg/morphology"
)

//go:embed names.dat
var namesDat []byte

func main() {
	// namesDat is not copied: it must outlive d (a package variable does).
	d, err := morphology.OpenBytes(namesDat)
	if err != nil {
		log.Fatal(err)
	}
	defer func() { _ = d.Close() }() // a no-op for OpenBytes

	for _, r := range d.Parse("Москвы") {
		fmt.Println(r.Word, "->", r.Normal, "("+r.Tag+")")
	}
	fmt.Println("source:", d.Info().Source)
	// Output:
	// москвы -> москва (GEO,gent)
	// source: names
}
